<?php
/**
* Implements hook_views_api().
*
* Enabling using templates inside module
*/
function oc_advent_calendar_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'oc_advent_calendar'),
    'template path' => drupal_get_path('module', 'oc_advent_calendar') . "/templates",
  );
}
/*
 * 
 */
function oc_advent_calendar_views_pre_render ( &$view ) { 
  /// check to make sure the view has a classname
  if ( $view->name == "oc_advent_calendar")  {
      drupal_add_js(drupal_get_path('module', 'oc_advent_calendar') ."/js/oc_advent_calendar.js");
      drupal_add_css(drupal_get_path('module', 'oc_advent_calendar') ."/css/oc-advent-calendar.css");
  }
}
/*
 * 
 */
function oc_advent_calendar_menu() {
  $items = array();
  
   $items['oc/advent/ajax/response'] = array(
    'page callback' => 'oc_advent_calendar_contact_form', // Render HTML
    'description' => 'Handles contact form ajax requests from the calendar',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
   );
  
  return $items;
}
function oc_advent_calendar_contact_form()
{
    /*
     * Send a email to the competition managers.
     */
    if(isset($_GET['Email']) && $_GET['Dayindex'] && $_GET['Name'] && $_GET['Text'] && $_GET['Tlf'])
    {
     $from = $_GET['Email'];
     $my_module = 'oc_advent_calendar';
     $my_mail_token = microtime();
     $message = array(
                'id' => $my_module . '_' . $my_mail_token,
                'to' => 'tfpet@odense.dk',
                'subject' => $_GET['Dayindex'] ." december",
                'body' => array($_GET['Name']." svarer:<br/><br/>".$_GET['Text'] + "<br/><br/> Telefon: " + $_GET['Tlf']),
                'headers' => array(
                    'From' => $from,
                    'Sender' => $from,
                    'Return-Path' => $from,
                ),
            );
            $system = drupal_mail_system($my_module, $my_mail_token);
            $message = $system->format($message);
            if ($system->mail($message)) {
                echo json_encode(1);
               
            } else {
                echo json_encode(0);
            }
            
    }
    else
    {
        echo json_encode(0);
    }
    drupal_exit();
}
function oc_advent_calendar_user_has_role($role_name, $user = NULL) {
if ($user == NULL) {
global $user;
}
if (is_array($user->roles) && in_array($role_name, array_values($user->roles))) {
return TRUE;
}

return FALSE;
}